# Generated by Django 5.1.15 on 2026-03-20 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('tag', models.CharField(blank=True, choices=[('bug', 'Bug'), ('feature', 'Feature'), ('refactor', 'Refactor'), ('docs', 'Docs'), ('test', 'Test'), ('deploy', 'Deploy'), ('config', 'Config'), ('other', 'Other')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('cwd', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminals', to='core.project')),
            ],
            options={
                'db_table': 'terminals',
                'ordering': ['-last_activity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_path', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('message_count', models.IntegerField(default=0)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.project')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.terminal')),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('response_summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('wip', 'WIP'), ('success', 'Success'), ('fail', 'Fail')], default='wip', max_length=10)),
                ('tag', models.CharField(blank=True, choices=[('bug', 'Bug'), ('feature', 'Feature'), ('refactor', 'Refactor'), ('docs', 'Docs'), ('test', 'Test'), ('deploy', 'Deploy'), ('config', 'Config'), ('other', 'Other')], max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('hook', 'Hook'), ('import', 'Import')], default='manual', max_length=20)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.prompt')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='core.project')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='core.terminal')),
            ],
            options={
                'db_table': 'prompts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=255)),
                ('tool_input_summary', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='core.prompt')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='core.session')),
            ],
            options={
                'db_table': 'tool_calls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['project'], name='idx_prompts_project_v2'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['status'], name='idx_prompts_status_v2'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['tag'], name='idx_prompts_tag_v2'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['parent'], name='idx_prompts_parent_v2'),
        ),
    ]
