# Generated by Django 5.1.15 on 2026-03-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_cache_create_tokens',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='total_cache_read_tokens',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='total_input_tokens',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='total_output_tokens',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
