# Generated by Django 5.1.15 on 2026-03-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_total_cache_create_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='screenshot',
            field=models.CharField(blank=True, help_text='Screenshot file path', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text='Project web URL for screenshot capture', null=True),
        ),
    ]
