# Generated by Django 5.1.15 on 2026-03-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_screenshot_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deploy_url',
            field=models.URLField(blank=True, help_text='Production/deployed URL', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='server_info',
            field=models.CharField(blank=True, help_text='Server/host info (e.g. 100서버, 80서버, MacBook)', max_length=500, null=True),
        ),
    ]
