# Generated by Django 5.1.15 on 2026-03-20 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_deploy_url_server_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('service_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('dev', 'Dev'), ('prod', 'Prod'), ('api', 'API'), ('db', 'Database'), ('cache', 'Cache'), ('other', 'Other')], default='dev', max_length=20)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('tcp', 'TCP')], default='http', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core.project')),
            ],
            options={
                'db_table': 'service_ports',
                'ordering': ['server_name', 'port'],
                'unique_together': {('ip', 'port')},
            },
        ),
    ]
