# Generated by Django 5.1.15 on 2026-03-21 09:39

from django.db import migrations


def migrate_screenshots(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    ProjectScreenshot = apps.get_model('core', 'ProjectScreenshot')
    for project in Project.objects.exclude(screenshot__isnull=True).exclude(screenshot=''):
        ProjectScreenshot.objects.get_or_create(
            project=project,
            filepath=project.screenshot,
            defaults={'order': 0},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projectscreenshot'),
    ]

    operations = [
        migrations.RunPython(migrate_screenshots, migrations.RunPython.noop),
    ]
