# Generated by Django 5.1.15 on 2026-03-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_github_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favorited',
            field=models.BooleanField(default=False, help_text='Heart-marked active project'),
        ),
    ]
