# Generated by Django 5.1.15 on 2026-03-21 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_project_favorited'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('task', 'Task'), ('deploy', 'Deploy')], default='task', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='core.project')),
            ],
            options={
                'db_table': 'project_todos',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
