# Generated by Django 5.1.15 on 2026-03-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_projecttodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceport',
            name='docker_container',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceport',
            name='docker_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='serviceport',
            name='is_docker',
            field=models.BooleanField(default=False),
        ),
    ]
