# Generated by Django 5.1.15 on 2026-03-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_serviceport_docker_container_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=500, unique=True)),
                ('bot_username', models.CharField(max_length=255)),
                ('bot_name', models.CharField(blank=True, default='', max_length=255)),
                ('chat_id', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'telegram_bots',
                'ordering': ['-created_at'],
            },
        ),
    ]
