# Generated by Django 5.1.15 on 2026-03-22 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_telegrambot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='chat_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='TelegramChatId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_ids', to='core.telegrambot')),
            ],
            options={
                'db_table': 'telegram_chat_ids',
                'ordering': ['created_at'],
                'unique_together': {('bot', 'chat_id')},
            },
        ),
    ]
