# Generated by Django 5.1.15 on 2026-04-13 14:57

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_project_owner_project_visibility_comment_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederatedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_prompt_id', models.IntegerField()),
                ('content', models.TextField()),
                ('response_summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('wip', 'WIP'), ('success', 'Success'), ('fail', 'Fail')], default='wip', max_length=10)),
                ('tag', models.CharField(blank=True, default='', max_length=20)),
                ('remote_created_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'federated_prompts',
                'ordering': ['-remote_created_at'],
            },
        ),
        migrations.CreateModel(
            name='FederatedServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Base URL of remote server', unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('our_token', models.CharField(default=secrets.token_urlsafe, help_text='Token we send to them', max_length=128)),
                ('their_token', models.CharField(blank=True, default='', help_text='Token they send to us', max_length=128)),
                ('shared_secret', models.CharField(blank=True, default='', help_text='Derived shared secret for HMAC', max_length=128)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('requests_today', models.IntegerField(default=0)),
                ('requests_reset_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'federated_servers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServerIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255, unique=True)),
                ('server_url', models.URLField(help_text='Public URL of this CPM server')),
                ('description', models.TextField(blank=True, default='')),
                ('shared_secret', models.CharField(default=secrets.token_urlsafe, max_length=128)),
                ('admin_contact', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Server Identity',
                'db_table': 'server_identity',
            },
        ),
        migrations.CreateModel(
            name='FederatedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_federated_id', models.CharField(blank=True, default='', help_text='username@server for remote authors', max_length=500)),
                ('content', models.TextField(max_length=2000)),
                ('remote_comment_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='federated_comments', to='core.prompt')),
                ('federated_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='federated_comments', to='core.federatedprompt')),
            ],
            options={
                'db_table': 'federated_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FederatedSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_project_id', models.IntegerField()),
                ('remote_project_name', models.CharField(max_length=255)),
                ('last_prompt_id', models.IntegerField(default=0, help_text='Sync cursor')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_project', models.ForeignKey(blank=True, help_text='Local mirror project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federation_subscriptions', to='core.project')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.federatedserver')),
            ],
            options={
                'db_table': 'federated_subscriptions',
                'unique_together': {('server', 'remote_project_id')},
            },
        ),
        migrations.AddField(
            model_name='federatedprompt',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='core.federatedsubscription'),
        ),
        migrations.CreateModel(
            name='FederatedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('federated_id', models.CharField(db_index=True, help_text='username@server-domain', max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.federatedserver')),
            ],
            options={
                'db_table': 'federated_users',
            },
        ),
        migrations.AddField(
            model_name='federatedprompt',
            name='remote_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.federateduser'),
        ),
        migrations.AlterUniqueTogether(
            name='federatedprompt',
            unique_together={('subscription', 'remote_prompt_id')},
        ),
    ]
