# Generated by Django 5.1.15 on 2026-04-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_federation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_sheet_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_sheet_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_sheet_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
