# Generated by Django 5.1.15 on 2026-04-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_is_approved_to_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreApprovedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pre_approved_emails',
            },
        ),
    ]
